language: node_js
node_js:
  - "0.10"
rvm:
  - 1.9.3
before_install:
  - "npm install"
  - "npm install -g grunt-cli"
  - "cd test"
install:
  - "npm install"
  - "bundle install --without development --deployment"
script:
  - "grunt spec:unit spec:e2e"
  - "bundle exec rspec"
cache:
  directories:
    - node_modules
    - test/vendor/bundle
    - test/node_modules
