language: node_js
node_js:
  - "0.10"
rvm:
  - 1.9.3
before_install:
  - "npm install"
  - "cd test"
install:
  - "npm install"
  - "bundle install --without development"
script:
  - "grunt spec:unit spec:e2e"
  - "bundle exec rspec"
