language: node_js
node_js:
  - "0.10"
env:
  - HEADLESS=true
before_install:
  - "npm install"
  - "npm install -g grunt-cli"
  - "cd test"
install: "npm install"
script:
  - "grunt spec:unit"
  - "grunt spec:e2e"
cache:
  directories:
    - node_modules
    - test/node_modules
    - test/bin
